/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockUSDC__factory } from './MockUSDC__factory.js';
export { MockUSDT__factory } from './MockUSDT__factory.js';
export { XsollaItems__factory } from './XsollaItems__factory.js';
export { XsollaMarket__factory } from './XsollaMarket__factory.js';
export { XsollaShop__factory } from './XsollaShop__factory.js';
export { XsollaToken__factory } from './XsollaToken__factory.js';
export { XsollaTreasury__factory } from './XsollaTreasury__factory.js';