import hiddenhidden from '../../assets/game/card_back.png';

const svg = (name) => `${import.meta.env.BASE_URL}cards-svg/${name}.svg`;

export default {
  hiddenhidden,
  c2: svg('c2'),
  c3: svg('c3'),
  c4: svg('c4'),
  c5: svg('c5'),
  c6: svg('c6'),
  c7: svg('c7'),
  c8: svg('c8'),
  c9: svg('c9'),
  c10: svg('c10'),
  cJ: svg('cJ'),
  cQ: svg('cQ'),
  cK: svg('cK'),
  cA: svg('cA'),
  d2: svg('d2'),
  d3: svg('d3'),
  d4: svg('d4'),
  d5: svg('d5'),
  d6: svg('d6'),
  d7: svg('d7'),
  d8: svg('d8'),
  d9: svg('d9'),
  d10: svg('d10'),
  dJ: svg('dJ'),
  dQ: svg('dQ'),
  dK: svg('dK'),
  dA: svg('dA'),
  h2: svg('h2'),
  h3: svg('h3'),
  h4: svg('h4'),
  h5: svg('h5'),
  h6: svg('h6'),
  h7: svg('h7'),
  h8: svg('h8'),
  h9: svg('h9'),
  h10: svg('h10'),
  hJ: svg('hJ'),
  hQ: svg('hQ'),
  hK: svg('hK'),
  hA: svg('hA'),
  s2: svg('s2'),
  s3: svg('s3'),
  s4: svg('s4'),
  s5: svg('s5'),
  s6: svg('s6'),
  s7: svg('s7'),
  s8: svg('s8'),
  s9: svg('s9'),
  s10: svg('s10'),
  sJ: svg('sJ'),
  sQ: svg('sQ'),
  sK: svg('sK'),
  sA: svg('sA'),
};
