/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface XsollaTreasuryInterface extends Interface {
    getFunction(nameOrSignature: "TIER1" | "TIER2" | "TIER3" | "buyXsolla" | "buyXsollaWithUsdc" | "buyXsollaWithUsdt" | "cancelUnstake" | "claimPlayReward" | "completeUnstake" | "demoMode" | "deposit" | "fundUsdc" | "fundUsdt" | "marketFeeBps" | "operator" | "operatorCredit" | "owner" | "pendingUnstake" | "playCredits" | "quoteUsdcToXsolla" | "quoteUsdtToXsolla" | "quoteXsollaToUsdc" | "quoteXsollaToUsdt" | "release" | "renounceOwnership" | "requestUnstake" | "setDemoMode" | "setOperator" | "setUnstakeDelay" | "setUsdc" | "setUsdcPerXsolla" | "setUsdt" | "setUsdtPerXsolla" | "shopDiscountBps" | "stake" | "stakeTier" | "staked" | "stakedBalance" | "swapUsdcForXsolla" | "swapUsdtForXsolla" | "swapXsollaForNative" | "swapXsollaForUsdc" | "swapXsollaForUsdt" | "token" | "transferOwnership" | "unstake" | "unstakeDelay" | "unstakeUnlockAt" | "usdc" | "usdcLiquidity" | "usdcPerXsolla" | "usdt" | "usdtLiquidity" | "usdtPerXsolla" | "withdrawPlayCredits"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Bought" | "BoughtWithUsdc" | "BoughtWithUsdt" | "DemoModeUpdated" | "Deposited" | "OperatorUpdated" | "OwnershipTransferred" | "RewardsClaimed" | "Staked" | "Swapped" | "SwappedUsdcForXsolla" | "SwappedUsdtForXsolla" | "SwappedXsollaForUsdc" | "SwappedXsollaForUsdt" | "UnstakeCancelled" | "UnstakeCompleted" | "UnstakeDelayUpdated" | "UnstakeRequested" | "Unstaked" | "UsdcRateUpdated" | "UsdcUpdated" | "UsdtRateUpdated" | "UsdtUpdated" | "Withdrawn"): EventFragment;

    encodeFunctionData(functionFragment: 'TIER1', values?: undefined): string;
encodeFunctionData(functionFragment: 'TIER2', values?: undefined): string;
encodeFunctionData(functionFragment: 'TIER3', values?: undefined): string;
encodeFunctionData(functionFragment: 'buyXsolla', values?: undefined): string;
encodeFunctionData(functionFragment: 'buyXsollaWithUsdc', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'buyXsollaWithUsdt', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelUnstake', values?: undefined): string;
encodeFunctionData(functionFragment: 'claimPlayReward', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'completeUnstake', values?: undefined): string;
encodeFunctionData(functionFragment: 'demoMode', values?: undefined): string;
encodeFunctionData(functionFragment: 'deposit', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'fundUsdc', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'fundUsdt', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'marketFeeBps', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'operator', values?: undefined): string;
encodeFunctionData(functionFragment: 'operatorCredit', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pendingUnstake', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'playCredits', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'quoteUsdcToXsolla', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'quoteUsdtToXsolla', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'quoteXsollaToUsdc', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'quoteXsollaToUsdt', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'release', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'requestUnstake', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setDemoMode', values: [boolean]): string;
encodeFunctionData(functionFragment: 'setOperator', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setUnstakeDelay', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setUsdc', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setUsdcPerXsolla', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setUsdt', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setUsdtPerXsolla', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'shopDiscountBps', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'stake', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'stakeTier', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'staked', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'stakedBalance', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'swapUsdcForXsolla', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'swapUsdtForXsolla', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'swapXsollaForNative', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'swapXsollaForUsdc', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'swapXsollaForUsdt', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'token', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'unstake', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'unstakeDelay', values?: undefined): string;
encodeFunctionData(functionFragment: 'unstakeUnlockAt', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'usdc', values?: undefined): string;
encodeFunctionData(functionFragment: 'usdcLiquidity', values?: undefined): string;
encodeFunctionData(functionFragment: 'usdcPerXsolla', values?: undefined): string;
encodeFunctionData(functionFragment: 'usdt', values?: undefined): string;
encodeFunctionData(functionFragment: 'usdtLiquidity', values?: undefined): string;
encodeFunctionData(functionFragment: 'usdtPerXsolla', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdrawPlayCredits', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'TIER1', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'TIER2', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'TIER3', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buyXsolla', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buyXsollaWithUsdc', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buyXsollaWithUsdt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelUnstake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimPlayReward', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'completeUnstake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'demoMode', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fundUsdc', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fundUsdt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'marketFeeBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'operator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'operatorCredit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingUnstake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'playCredits', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'quoteUsdcToXsolla', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'quoteUsdtToXsolla', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'quoteXsollaToUsdc', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'quoteXsollaToUsdt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'release', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestUnstake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setDemoMode', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setOperator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setUnstakeDelay', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setUsdc', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setUsdcPerXsolla', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setUsdt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setUsdtPerXsolla', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'shopDiscountBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stakeTier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'staked', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stakedBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swapUsdcForXsolla', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swapUsdtForXsolla', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swapXsollaForNative', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swapXsollaForUsdc', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swapXsollaForUsdt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'token', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unstake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unstakeDelay', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unstakeUnlockAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdc', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdcLiquidity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdcPerXsolla', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdtLiquidity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdtPerXsolla', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawPlayCredits', data: BytesLike): Result;
  }

  
    export namespace BoughtEvent {
      export type InputTuple = [user: AddressLike, amount: BigNumberish];
      export type OutputTuple = [user: string, amount: bigint];
      export interface OutputObject {user: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BoughtWithUsdcEvent {
      export type InputTuple = [user: AddressLike, xsollaAmount: BigNumberish, usdcAmount: BigNumberish];
      export type OutputTuple = [user: string, xsollaAmount: bigint, usdcAmount: bigint];
      export interface OutputObject {user: string, xsollaAmount: bigint, usdcAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BoughtWithUsdtEvent {
      export type InputTuple = [user: AddressLike, xsollaAmount: BigNumberish, usdtAmount: BigNumberish];
      export type OutputTuple = [user: string, xsollaAmount: bigint, usdtAmount: bigint];
      export interface OutputObject {user: string, xsollaAmount: bigint, usdtAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DemoModeUpdatedEvent {
      export type InputTuple = [enabled: boolean];
      export type OutputTuple = [enabled: boolean];
      export interface OutputObject {enabled: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DepositedEvent {
      export type InputTuple = [user: AddressLike, amount: BigNumberish];
      export type OutputTuple = [user: string, amount: bigint];
      export interface OutputObject {user: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OperatorUpdatedEvent {
      export type InputTuple = [operator: AddressLike];
      export type OutputTuple = [operator: string];
      export interface OutputObject {operator: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RewardsClaimedEvent {
      export type InputTuple = [user: AddressLike, amount: BigNumberish];
      export type OutputTuple = [user: string, amount: bigint];
      export interface OutputObject {user: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StakedEvent {
      export type InputTuple = [user: AddressLike, amount: BigNumberish];
      export type OutputTuple = [user: string, amount: bigint];
      export interface OutputObject {user: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SwappedEvent {
      export type InputTuple = [user: AddressLike, amount: BigNumberish];
      export type OutputTuple = [user: string, amount: bigint];
      export interface OutputObject {user: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SwappedUsdcForXsollaEvent {
      export type InputTuple = [user: AddressLike, usdcAmount: BigNumberish, xsollaAmount: BigNumberish];
      export type OutputTuple = [user: string, usdcAmount: bigint, xsollaAmount: bigint];
      export interface OutputObject {user: string, usdcAmount: bigint, xsollaAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SwappedUsdtForXsollaEvent {
      export type InputTuple = [user: AddressLike, usdtAmount: BigNumberish, xsollaAmount: BigNumberish];
      export type OutputTuple = [user: string, usdtAmount: bigint, xsollaAmount: bigint];
      export interface OutputObject {user: string, usdtAmount: bigint, xsollaAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SwappedXsollaForUsdcEvent {
      export type InputTuple = [user: AddressLike, xsollaAmount: BigNumberish, usdcAmount: BigNumberish];
      export type OutputTuple = [user: string, xsollaAmount: bigint, usdcAmount: bigint];
      export interface OutputObject {user: string, xsollaAmount: bigint, usdcAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SwappedXsollaForUsdtEvent {
      export type InputTuple = [user: AddressLike, xsollaAmount: BigNumberish, usdtAmount: BigNumberish];
      export type OutputTuple = [user: string, xsollaAmount: bigint, usdtAmount: bigint];
      export interface OutputObject {user: string, xsollaAmount: bigint, usdtAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnstakeCancelledEvent {
      export type InputTuple = [user: AddressLike, amount: BigNumberish];
      export type OutputTuple = [user: string, amount: bigint];
      export interface OutputObject {user: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnstakeCompletedEvent {
      export type InputTuple = [user: AddressLike, amount: BigNumberish];
      export type OutputTuple = [user: string, amount: bigint];
      export interface OutputObject {user: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnstakeDelayUpdatedEvent {
      export type InputTuple = [unstakeDelay: BigNumberish];
      export type OutputTuple = [unstakeDelay: bigint];
      export interface OutputObject {unstakeDelay: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnstakeRequestedEvent {
      export type InputTuple = [user: AddressLike, amount: BigNumberish, unlockAt: BigNumberish];
      export type OutputTuple = [user: string, amount: bigint, unlockAt: bigint];
      export interface OutputObject {user: string, amount: bigint, unlockAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnstakedEvent {
      export type InputTuple = [user: AddressLike, amount: BigNumberish];
      export type OutputTuple = [user: string, amount: bigint];
      export interface OutputObject {user: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UsdcRateUpdatedEvent {
      export type InputTuple = [usdcPerXsolla: BigNumberish];
      export type OutputTuple = [usdcPerXsolla: bigint];
      export interface OutputObject {usdcPerXsolla: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UsdcUpdatedEvent {
      export type InputTuple = [usdc: AddressLike];
      export type OutputTuple = [usdc: string];
      export interface OutputObject {usdc: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UsdtRateUpdatedEvent {
      export type InputTuple = [usdtPerXsolla: BigNumberish];
      export type OutputTuple = [usdtPerXsolla: bigint];
      export interface OutputObject {usdtPerXsolla: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UsdtUpdatedEvent {
      export type InputTuple = [usdt: AddressLike];
      export type OutputTuple = [usdt: string];
      export interface OutputObject {usdt: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawnEvent {
      export type InputTuple = [user: AddressLike, amount: BigNumberish];
      export type OutputTuple = [user: string, amount: bigint];
      export interface OutputObject {user: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface XsollaTreasury extends BaseContract {
    
    connect(runner?: ContractRunner | null): XsollaTreasury;
    waitForDeployment(): Promise<this>;

    interface: XsollaTreasuryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    TIER1: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    TIER2: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    TIER3: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    buyXsolla: TypedContractMethod<
      [],
      [void],
      'payable'
    >
    

    
    buyXsollaWithUsdc: TypedContractMethod<
      [usdcAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    buyXsollaWithUsdt: TypedContractMethod<
      [usdtAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    cancelUnstake: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    claimPlayReward: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    completeUnstake: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    demoMode: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    deposit: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    fundUsdc: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    fundUsdt: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    marketFeeBps: TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    operator: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    operatorCredit: TypedContractMethod<
      [user: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pendingUnstake: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    playCredits: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    quoteUsdcToXsolla: TypedContractMethod<
      [usdcAmount: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    quoteUsdtToXsolla: TypedContractMethod<
      [usdtAmount: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    quoteXsollaToUsdc: TypedContractMethod<
      [xsollaAmount: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    quoteXsollaToUsdt: TypedContractMethod<
      [xsollaAmount: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    release: TypedContractMethod<
      [user: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    requestUnstake: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setDemoMode: TypedContractMethod<
      [enabled: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setOperator: TypedContractMethod<
      [newOperator: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setUnstakeDelay: TypedContractMethod<
      [delay: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setUsdc: TypedContractMethod<
      [usdcAddress: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setUsdcPerXsolla: TypedContractMethod<
      [rate: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setUsdt: TypedContractMethod<
      [usdtAddress: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setUsdtPerXsolla: TypedContractMethod<
      [rate: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    shopDiscountBps: TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    stake: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    stakeTier: TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    staked: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    stakedBalance: TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    swapUsdcForXsolla: TypedContractMethod<
      [usdcAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    swapUsdtForXsolla: TypedContractMethod<
      [usdtAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    swapXsollaForNative: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    swapXsollaForUsdc: TypedContractMethod<
      [xsollaAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    swapXsollaForUsdt: TypedContractMethod<
      [xsollaAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    token: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    unstake: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    unstakeDelay: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    unstakeUnlockAt: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    usdc: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    usdcLiquidity: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    usdcPerXsolla: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    usdt: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    usdtLiquidity: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    usdtPerXsolla: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    withdrawPlayCredits: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'TIER1'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'TIER2'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'TIER3'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'buyXsolla'): TypedContractMethod<
      [],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'buyXsollaWithUsdc'): TypedContractMethod<
      [usdcAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'buyXsollaWithUsdt'): TypedContractMethod<
      [usdtAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cancelUnstake'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimPlayReward'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'completeUnstake'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'demoMode'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'fundUsdc'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'fundUsdt'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'marketFeeBps'): TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'operator'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'operatorCredit'): TypedContractMethod<
      [user: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pendingUnstake'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'playCredits'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'quoteUsdcToXsolla'): TypedContractMethod<
      [usdcAmount: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'quoteUsdtToXsolla'): TypedContractMethod<
      [usdtAmount: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'quoteXsollaToUsdc'): TypedContractMethod<
      [xsollaAmount: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'quoteXsollaToUsdt'): TypedContractMethod<
      [xsollaAmount: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'release'): TypedContractMethod<
      [user: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'requestUnstake'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setDemoMode'): TypedContractMethod<
      [enabled: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setOperator'): TypedContractMethod<
      [newOperator: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setUnstakeDelay'): TypedContractMethod<
      [delay: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setUsdc'): TypedContractMethod<
      [usdcAddress: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setUsdcPerXsolla'): TypedContractMethod<
      [rate: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setUsdt'): TypedContractMethod<
      [usdtAddress: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setUsdtPerXsolla'): TypedContractMethod<
      [rate: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'shopDiscountBps'): TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'stake'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'stakeTier'): TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'staked'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'stakedBalance'): TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'swapUsdcForXsolla'): TypedContractMethod<
      [usdcAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'swapUsdtForXsolla'): TypedContractMethod<
      [usdtAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'swapXsollaForNative'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'swapXsollaForUsdc'): TypedContractMethod<
      [xsollaAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'swapXsollaForUsdt'): TypedContractMethod<
      [xsollaAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'token'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unstake'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unstakeDelay'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'unstakeUnlockAt'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'usdc'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'usdcLiquidity'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'usdcPerXsolla'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'usdt'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'usdtLiquidity'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'usdtPerXsolla'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'withdrawPlayCredits'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Bought'): TypedContractEvent<BoughtEvent.InputTuple, BoughtEvent.OutputTuple, BoughtEvent.OutputObject>;
getEvent(key: 'BoughtWithUsdc'): TypedContractEvent<BoughtWithUsdcEvent.InputTuple, BoughtWithUsdcEvent.OutputTuple, BoughtWithUsdcEvent.OutputObject>;
getEvent(key: 'BoughtWithUsdt'): TypedContractEvent<BoughtWithUsdtEvent.InputTuple, BoughtWithUsdtEvent.OutputTuple, BoughtWithUsdtEvent.OutputObject>;
getEvent(key: 'DemoModeUpdated'): TypedContractEvent<DemoModeUpdatedEvent.InputTuple, DemoModeUpdatedEvent.OutputTuple, DemoModeUpdatedEvent.OutputObject>;
getEvent(key: 'Deposited'): TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
getEvent(key: 'OperatorUpdated'): TypedContractEvent<OperatorUpdatedEvent.InputTuple, OperatorUpdatedEvent.OutputTuple, OperatorUpdatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'RewardsClaimed'): TypedContractEvent<RewardsClaimedEvent.InputTuple, RewardsClaimedEvent.OutputTuple, RewardsClaimedEvent.OutputObject>;
getEvent(key: 'Staked'): TypedContractEvent<StakedEvent.InputTuple, StakedEvent.OutputTuple, StakedEvent.OutputObject>;
getEvent(key: 'Swapped'): TypedContractEvent<SwappedEvent.InputTuple, SwappedEvent.OutputTuple, SwappedEvent.OutputObject>;
getEvent(key: 'SwappedUsdcForXsolla'): TypedContractEvent<SwappedUsdcForXsollaEvent.InputTuple, SwappedUsdcForXsollaEvent.OutputTuple, SwappedUsdcForXsollaEvent.OutputObject>;
getEvent(key: 'SwappedUsdtForXsolla'): TypedContractEvent<SwappedUsdtForXsollaEvent.InputTuple, SwappedUsdtForXsollaEvent.OutputTuple, SwappedUsdtForXsollaEvent.OutputObject>;
getEvent(key: 'SwappedXsollaForUsdc'): TypedContractEvent<SwappedXsollaForUsdcEvent.InputTuple, SwappedXsollaForUsdcEvent.OutputTuple, SwappedXsollaForUsdcEvent.OutputObject>;
getEvent(key: 'SwappedXsollaForUsdt'): TypedContractEvent<SwappedXsollaForUsdtEvent.InputTuple, SwappedXsollaForUsdtEvent.OutputTuple, SwappedXsollaForUsdtEvent.OutputObject>;
getEvent(key: 'UnstakeCancelled'): TypedContractEvent<UnstakeCancelledEvent.InputTuple, UnstakeCancelledEvent.OutputTuple, UnstakeCancelledEvent.OutputObject>;
getEvent(key: 'UnstakeCompleted'): TypedContractEvent<UnstakeCompletedEvent.InputTuple, UnstakeCompletedEvent.OutputTuple, UnstakeCompletedEvent.OutputObject>;
getEvent(key: 'UnstakeDelayUpdated'): TypedContractEvent<UnstakeDelayUpdatedEvent.InputTuple, UnstakeDelayUpdatedEvent.OutputTuple, UnstakeDelayUpdatedEvent.OutputObject>;
getEvent(key: 'UnstakeRequested'): TypedContractEvent<UnstakeRequestedEvent.InputTuple, UnstakeRequestedEvent.OutputTuple, UnstakeRequestedEvent.OutputObject>;
getEvent(key: 'Unstaked'): TypedContractEvent<UnstakedEvent.InputTuple, UnstakedEvent.OutputTuple, UnstakedEvent.OutputObject>;
getEvent(key: 'UsdcRateUpdated'): TypedContractEvent<UsdcRateUpdatedEvent.InputTuple, UsdcRateUpdatedEvent.OutputTuple, UsdcRateUpdatedEvent.OutputObject>;
getEvent(key: 'UsdcUpdated'): TypedContractEvent<UsdcUpdatedEvent.InputTuple, UsdcUpdatedEvent.OutputTuple, UsdcUpdatedEvent.OutputObject>;
getEvent(key: 'UsdtRateUpdated'): TypedContractEvent<UsdtRateUpdatedEvent.InputTuple, UsdtRateUpdatedEvent.OutputTuple, UsdtRateUpdatedEvent.OutputObject>;
getEvent(key: 'UsdtUpdated'): TypedContractEvent<UsdtUpdatedEvent.InputTuple, UsdtUpdatedEvent.OutputTuple, UsdtUpdatedEvent.OutputObject>;
getEvent(key: 'Withdrawn'): TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;

    filters: {
      
      'Bought(address,uint256)': TypedContractEvent<BoughtEvent.InputTuple, BoughtEvent.OutputTuple, BoughtEvent.OutputObject>;
      Bought: TypedContractEvent<BoughtEvent.InputTuple, BoughtEvent.OutputTuple, BoughtEvent.OutputObject>;
    

      'BoughtWithUsdc(address,uint256,uint256)': TypedContractEvent<BoughtWithUsdcEvent.InputTuple, BoughtWithUsdcEvent.OutputTuple, BoughtWithUsdcEvent.OutputObject>;
      BoughtWithUsdc: TypedContractEvent<BoughtWithUsdcEvent.InputTuple, BoughtWithUsdcEvent.OutputTuple, BoughtWithUsdcEvent.OutputObject>;
    

      'BoughtWithUsdt(address,uint256,uint256)': TypedContractEvent<BoughtWithUsdtEvent.InputTuple, BoughtWithUsdtEvent.OutputTuple, BoughtWithUsdtEvent.OutputObject>;
      BoughtWithUsdt: TypedContractEvent<BoughtWithUsdtEvent.InputTuple, BoughtWithUsdtEvent.OutputTuple, BoughtWithUsdtEvent.OutputObject>;
    

      'DemoModeUpdated(bool)': TypedContractEvent<DemoModeUpdatedEvent.InputTuple, DemoModeUpdatedEvent.OutputTuple, DemoModeUpdatedEvent.OutputObject>;
      DemoModeUpdated: TypedContractEvent<DemoModeUpdatedEvent.InputTuple, DemoModeUpdatedEvent.OutputTuple, DemoModeUpdatedEvent.OutputObject>;
    

      'Deposited(address,uint256)': TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
      Deposited: TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
    

      'OperatorUpdated(address)': TypedContractEvent<OperatorUpdatedEvent.InputTuple, OperatorUpdatedEvent.OutputTuple, OperatorUpdatedEvent.OutputObject>;
      OperatorUpdated: TypedContractEvent<OperatorUpdatedEvent.InputTuple, OperatorUpdatedEvent.OutputTuple, OperatorUpdatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'RewardsClaimed(address,uint256)': TypedContractEvent<RewardsClaimedEvent.InputTuple, RewardsClaimedEvent.OutputTuple, RewardsClaimedEvent.OutputObject>;
      RewardsClaimed: TypedContractEvent<RewardsClaimedEvent.InputTuple, RewardsClaimedEvent.OutputTuple, RewardsClaimedEvent.OutputObject>;
    

      'Staked(address,uint256)': TypedContractEvent<StakedEvent.InputTuple, StakedEvent.OutputTuple, StakedEvent.OutputObject>;
      Staked: TypedContractEvent<StakedEvent.InputTuple, StakedEvent.OutputTuple, StakedEvent.OutputObject>;
    

      'Swapped(address,uint256)': TypedContractEvent<SwappedEvent.InputTuple, SwappedEvent.OutputTuple, SwappedEvent.OutputObject>;
      Swapped: TypedContractEvent<SwappedEvent.InputTuple, SwappedEvent.OutputTuple, SwappedEvent.OutputObject>;
    

      'SwappedUsdcForXsolla(address,uint256,uint256)': TypedContractEvent<SwappedUsdcForXsollaEvent.InputTuple, SwappedUsdcForXsollaEvent.OutputTuple, SwappedUsdcForXsollaEvent.OutputObject>;
      SwappedUsdcForXsolla: TypedContractEvent<SwappedUsdcForXsollaEvent.InputTuple, SwappedUsdcForXsollaEvent.OutputTuple, SwappedUsdcForXsollaEvent.OutputObject>;
    

      'SwappedUsdtForXsolla(address,uint256,uint256)': TypedContractEvent<SwappedUsdtForXsollaEvent.InputTuple, SwappedUsdtForXsollaEvent.OutputTuple, SwappedUsdtForXsollaEvent.OutputObject>;
      SwappedUsdtForXsolla: TypedContractEvent<SwappedUsdtForXsollaEvent.InputTuple, SwappedUsdtForXsollaEvent.OutputTuple, SwappedUsdtForXsollaEvent.OutputObject>;
    

      'SwappedXsollaForUsdc(address,uint256,uint256)': TypedContractEvent<SwappedXsollaForUsdcEvent.InputTuple, SwappedXsollaForUsdcEvent.OutputTuple, SwappedXsollaForUsdcEvent.OutputObject>;
      SwappedXsollaForUsdc: TypedContractEvent<SwappedXsollaForUsdcEvent.InputTuple, SwappedXsollaForUsdcEvent.OutputTuple, SwappedXsollaForUsdcEvent.OutputObject>;
    

      'SwappedXsollaForUsdt(address,uint256,uint256)': TypedContractEvent<SwappedXsollaForUsdtEvent.InputTuple, SwappedXsollaForUsdtEvent.OutputTuple, SwappedXsollaForUsdtEvent.OutputObject>;
      SwappedXsollaForUsdt: TypedContractEvent<SwappedXsollaForUsdtEvent.InputTuple, SwappedXsollaForUsdtEvent.OutputTuple, SwappedXsollaForUsdtEvent.OutputObject>;
    

      'UnstakeCancelled(address,uint256)': TypedContractEvent<UnstakeCancelledEvent.InputTuple, UnstakeCancelledEvent.OutputTuple, UnstakeCancelledEvent.OutputObject>;
      UnstakeCancelled: TypedContractEvent<UnstakeCancelledEvent.InputTuple, UnstakeCancelledEvent.OutputTuple, UnstakeCancelledEvent.OutputObject>;
    

      'UnstakeCompleted(address,uint256)': TypedContractEvent<UnstakeCompletedEvent.InputTuple, UnstakeCompletedEvent.OutputTuple, UnstakeCompletedEvent.OutputObject>;
      UnstakeCompleted: TypedContractEvent<UnstakeCompletedEvent.InputTuple, UnstakeCompletedEvent.OutputTuple, UnstakeCompletedEvent.OutputObject>;
    

      'UnstakeDelayUpdated(uint256)': TypedContractEvent<UnstakeDelayUpdatedEvent.InputTuple, UnstakeDelayUpdatedEvent.OutputTuple, UnstakeDelayUpdatedEvent.OutputObject>;
      UnstakeDelayUpdated: TypedContractEvent<UnstakeDelayUpdatedEvent.InputTuple, UnstakeDelayUpdatedEvent.OutputTuple, UnstakeDelayUpdatedEvent.OutputObject>;
    

      'UnstakeRequested(address,uint256,uint256)': TypedContractEvent<UnstakeRequestedEvent.InputTuple, UnstakeRequestedEvent.OutputTuple, UnstakeRequestedEvent.OutputObject>;
      UnstakeRequested: TypedContractEvent<UnstakeRequestedEvent.InputTuple, UnstakeRequestedEvent.OutputTuple, UnstakeRequestedEvent.OutputObject>;
    

      'Unstaked(address,uint256)': TypedContractEvent<UnstakedEvent.InputTuple, UnstakedEvent.OutputTuple, UnstakedEvent.OutputObject>;
      Unstaked: TypedContractEvent<UnstakedEvent.InputTuple, UnstakedEvent.OutputTuple, UnstakedEvent.OutputObject>;
    

      'UsdcRateUpdated(uint256)': TypedContractEvent<UsdcRateUpdatedEvent.InputTuple, UsdcRateUpdatedEvent.OutputTuple, UsdcRateUpdatedEvent.OutputObject>;
      UsdcRateUpdated: TypedContractEvent<UsdcRateUpdatedEvent.InputTuple, UsdcRateUpdatedEvent.OutputTuple, UsdcRateUpdatedEvent.OutputObject>;
    

      'UsdcUpdated(address)': TypedContractEvent<UsdcUpdatedEvent.InputTuple, UsdcUpdatedEvent.OutputTuple, UsdcUpdatedEvent.OutputObject>;
      UsdcUpdated: TypedContractEvent<UsdcUpdatedEvent.InputTuple, UsdcUpdatedEvent.OutputTuple, UsdcUpdatedEvent.OutputObject>;
    

      'UsdtRateUpdated(uint256)': TypedContractEvent<UsdtRateUpdatedEvent.InputTuple, UsdtRateUpdatedEvent.OutputTuple, UsdtRateUpdatedEvent.OutputObject>;
      UsdtRateUpdated: TypedContractEvent<UsdtRateUpdatedEvent.InputTuple, UsdtRateUpdatedEvent.OutputTuple, UsdtRateUpdatedEvent.OutputObject>;
    

      'UsdtUpdated(address)': TypedContractEvent<UsdtUpdatedEvent.InputTuple, UsdtUpdatedEvent.OutputTuple, UsdtUpdatedEvent.OutputObject>;
      UsdtUpdated: TypedContractEvent<UsdtUpdatedEvent.InputTuple, UsdtUpdatedEvent.OutputTuple, UsdtUpdatedEvent.OutputObject>;
    

      'Withdrawn(address,uint256)': TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
      Withdrawn: TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
    
    };
  }