/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface XsollaMarketInterface extends Interface {
    getFunction(nameOrSignature: "buy" | "cancel" | "feeBps" | "feeRecipient" | "getOffer" | "items" | "licenseFeeBps" | "licenseItemId" | "list" | "nextOfferId" | "offers" | "owner" | "renounceOwnership" | "setFees" | "setStakeView" | "shop" | "stakeView" | "transferOwnership" | "xsItems" | "xsolla"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "FeesUpdated" | "OfferCancelled" | "OfferListed" | "OfferSold" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'buy', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancel', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'feeBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'feeRecipient', values?: undefined): string;
encodeFunctionData(functionFragment: 'getOffer', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'items', values?: undefined): string;
encodeFunctionData(functionFragment: 'licenseFeeBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'licenseItemId', values?: undefined): string;
encodeFunctionData(functionFragment: 'list', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'nextOfferId', values?: undefined): string;
encodeFunctionData(functionFragment: 'offers', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setFees', values: [BigNumberish, BigNumberish, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'setStakeView', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'shop', values?: undefined): string;
encodeFunctionData(functionFragment: 'stakeView', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'xsItems', values?: undefined): string;
encodeFunctionData(functionFragment: 'xsolla', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'buy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancel', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeRecipient', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOffer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'items', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'licenseFeeBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'licenseItemId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'list', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextOfferId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'offers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setStakeView', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'shop', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stakeView', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'xsItems', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'xsolla', data: BytesLike): Result;
  }

  
    export namespace FeesUpdatedEvent {
      export type InputTuple = [feeBps: BigNumberish, licenseFeeBps: BigNumberish, licenseItemId: BigNumberish];
      export type OutputTuple = [feeBps: bigint, licenseFeeBps: bigint, licenseItemId: bigint];
      export interface OutputObject {feeBps: bigint, licenseFeeBps: bigint, licenseItemId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OfferCancelledEvent {
      export type InputTuple = [offerId: BigNumberish];
      export type OutputTuple = [offerId: bigint];
      export interface OutputObject {offerId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OfferListedEvent {
      export type InputTuple = [offerId: BigNumberish, seller: AddressLike, itemId: BigNumberish, quantity: BigNumberish, priceXsolla: BigNumberish];
      export type OutputTuple = [offerId: bigint, seller: string, itemId: bigint, quantity: bigint, priceXsolla: bigint];
      export interface OutputObject {offerId: bigint, seller: string, itemId: bigint, quantity: bigint, priceXsolla: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OfferSoldEvent {
      export type InputTuple = [offerId: BigNumberish, buyer: AddressLike, studio: AddressLike, itemId: BigNumberish, quantity: BigNumberish, studioPaid: BigNumberish, versePaid: BigNumberish, sellerPaid: BigNumberish];
      export type OutputTuple = [offerId: bigint, buyer: string, studio: string, itemId: bigint, quantity: bigint, studioPaid: bigint, versePaid: bigint, sellerPaid: bigint];
      export interface OutputObject {offerId: bigint, buyer: string, studio: string, itemId: bigint, quantity: bigint, studioPaid: bigint, versePaid: bigint, sellerPaid: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface XsollaMarket extends BaseContract {
    
    connect(runner?: ContractRunner | null): XsollaMarket;
    waitForDeployment(): Promise<this>;

    interface: XsollaMarketInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    buy: TypedContractMethod<
      [offerId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    cancel: TypedContractMethod<
      [offerId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    feeBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    feeRecipient: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getOffer: TypedContractMethod<
      [offerId: BigNumberish, ],
      [[string, bigint, bigint, bigint, boolean] & {seller: string, itemId: bigint, quantity: bigint, priceXsolla: bigint, active: boolean }],
      'view'
    >
    

    
    items: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    licenseFeeBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    licenseItemId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    list: TypedContractMethod<
      [itemId: BigNumberish, quantity: BigNumberish, priceXsolla: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    nextOfferId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    offers: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, bigint, bigint, boolean] & {seller: string, itemId: bigint, quantity: bigint, priceXsolla: bigint, active: boolean }],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setFees: TypedContractMethod<
      [feeBps_: BigNumberish, licenseFeeBps_: BigNumberish, licenseItemId_: BigNumberish, feeRecipient_: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setStakeView: TypedContractMethod<
      [stakeView_: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    shop: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    stakeView: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    xsItems: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    xsolla: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'buy'): TypedContractMethod<
      [offerId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cancel'): TypedContractMethod<
      [offerId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'feeBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'feeRecipient'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getOffer'): TypedContractMethod<
      [offerId: BigNumberish, ],
      [[string, bigint, bigint, bigint, boolean] & {seller: string, itemId: bigint, quantity: bigint, priceXsolla: bigint, active: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'items'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'licenseFeeBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'licenseItemId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'list'): TypedContractMethod<
      [itemId: BigNumberish, quantity: BigNumberish, priceXsolla: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'nextOfferId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'offers'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, bigint, bigint, boolean] & {seller: string, itemId: bigint, quantity: bigint, priceXsolla: bigint, active: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setFees'): TypedContractMethod<
      [feeBps_: BigNumberish, licenseFeeBps_: BigNumberish, licenseItemId_: BigNumberish, feeRecipient_: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setStakeView'): TypedContractMethod<
      [stakeView_: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'shop'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'stakeView'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'xsItems'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'xsolla'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'FeesUpdated'): TypedContractEvent<FeesUpdatedEvent.InputTuple, FeesUpdatedEvent.OutputTuple, FeesUpdatedEvent.OutputObject>;
getEvent(key: 'OfferCancelled'): TypedContractEvent<OfferCancelledEvent.InputTuple, OfferCancelledEvent.OutputTuple, OfferCancelledEvent.OutputObject>;
getEvent(key: 'OfferListed'): TypedContractEvent<OfferListedEvent.InputTuple, OfferListedEvent.OutputTuple, OfferListedEvent.OutputObject>;
getEvent(key: 'OfferSold'): TypedContractEvent<OfferSoldEvent.InputTuple, OfferSoldEvent.OutputTuple, OfferSoldEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'FeesUpdated(uint16,uint16,uint256)': TypedContractEvent<FeesUpdatedEvent.InputTuple, FeesUpdatedEvent.OutputTuple, FeesUpdatedEvent.OutputObject>;
      FeesUpdated: TypedContractEvent<FeesUpdatedEvent.InputTuple, FeesUpdatedEvent.OutputTuple, FeesUpdatedEvent.OutputObject>;
    

      'OfferCancelled(uint256)': TypedContractEvent<OfferCancelledEvent.InputTuple, OfferCancelledEvent.OutputTuple, OfferCancelledEvent.OutputObject>;
      OfferCancelled: TypedContractEvent<OfferCancelledEvent.InputTuple, OfferCancelledEvent.OutputTuple, OfferCancelledEvent.OutputObject>;
    

      'OfferListed(uint256,address,uint256,uint256,uint256)': TypedContractEvent<OfferListedEvent.InputTuple, OfferListedEvent.OutputTuple, OfferListedEvent.OutputObject>;
      OfferListed: TypedContractEvent<OfferListedEvent.InputTuple, OfferListedEvent.OutputTuple, OfferListedEvent.OutputObject>;
    

      'OfferSold(uint256,address,address,uint256,uint256,uint256,uint256,uint256)': TypedContractEvent<OfferSoldEvent.InputTuple, OfferSoldEvent.OutputTuple, OfferSoldEvent.OutputObject>;
      OfferSold: TypedContractEvent<OfferSoldEvent.InputTuple, OfferSoldEvent.OutputTuple, OfferSoldEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }