/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface XsollaShopInterface extends Interface {
    getFunction(nameOrSignature: "MAX_STUDIO_BPS" | "buy" | "games" | "getGame" | "getListing" | "isStudio" | "itemGameId" | "items" | "listEcosystemItem" | "listForStudio" | "listItem" | "listingEconomy" | "listings" | "nextGameId" | "nextItemId" | "owner" | "paymentRecipient" | "registerGame" | "registerGameFor" | "renounceOwnership" | "setPaymentRecipient" | "setStakeView" | "setStudio" | "stakeView" | "transferOwnership" | "updateItem" | "updateOwnGame" | "updateOwnItem" | "xsolla"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "GameRegistered" | "GameUpdated" | "ItemListed" | "ItemPurchased" | "ItemUpdated" | "OwnershipTransferred" | "PaymentRecipientUpdated" | "StakeViewUpdated" | "StudioUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'MAX_STUDIO_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'buy', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'games', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getGame', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getListing', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'isStudio', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'itemGameId', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'items', values?: undefined): string;
encodeFunctionData(functionFragment: 'listEcosystemItem', values: [BigNumberish, string, string, string, string, string, AddressLike, BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'listForStudio', values: [BigNumberish, string, string, BigNumberish, string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'listItem', values: [BigNumberish, string, string, string]): string;
encodeFunctionData(functionFragment: 'listingEconomy', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'listings', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'nextGameId', values?: undefined): string;
encodeFunctionData(functionFragment: 'nextItemId', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'paymentRecipient', values?: undefined): string;
encodeFunctionData(functionFragment: 'registerGame', values: [string, string, string, string, string]): string;
encodeFunctionData(functionFragment: 'registerGameFor', values: [AddressLike, string, string, string, string, string]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setPaymentRecipient', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setStakeView', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setStudio', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'stakeView', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateItem', values: [BigNumberish, BigNumberish, boolean, string, string, string]): string;
encodeFunctionData(functionFragment: 'updateOwnGame', values: [BigNumberish, string, string, string, string, string, boolean]): string;
encodeFunctionData(functionFragment: 'updateOwnItem', values: [BigNumberish, BigNumberish, boolean, string, string, string]): string;
encodeFunctionData(functionFragment: 'xsolla', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'MAX_STUDIO_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'games', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getGame', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getListing', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isStudio', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'itemGameId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'items', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'listEcosystemItem', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'listForStudio', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'listItem', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'listingEconomy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'listings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextGameId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextItemId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paymentRecipient', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerGame', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerGameFor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPaymentRecipient', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setStakeView', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setStudio', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stakeView', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateItem', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateOwnGame', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateOwnItem', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'xsolla', data: BytesLike): Result;
  }

  
    export namespace GameRegisteredEvent {
      export type InputTuple = [gameId: BigNumberish, studio: AddressLike, name: string];
      export type OutputTuple = [gameId: bigint, studio: string, name: string];
      export interface OutputObject {gameId: bigint, studio: string, name: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace GameUpdatedEvent {
      export type InputTuple = [gameId: BigNumberish, name: string, active: boolean];
      export type OutputTuple = [gameId: bigint, name: string, active: boolean];
      export interface OutputObject {gameId: bigint, name: string, active: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ItemListedEvent {
      export type InputTuple = [itemId: BigNumberish, priceXsolla: BigNumberish, name: string, metadataURI: string, game: string, kind: string, studio: AddressLike, studioBps: BigNumberish];
      export type OutputTuple = [itemId: bigint, priceXsolla: bigint, name: string, metadataURI: string, game: string, kind: string, studio: string, studioBps: bigint];
      export interface OutputObject {itemId: bigint, priceXsolla: bigint, name: string, metadataURI: string, game: string, kind: string, studio: string, studioBps: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ItemPurchasedEvent {
      export type InputTuple = [buyer: AddressLike, itemId: BigNumberish, studio: AddressLike, quantity: BigNumberish, totalPaid: BigNumberish, studioPaid: BigNumberish, versePaid: BigNumberish];
      export type OutputTuple = [buyer: string, itemId: bigint, studio: string, quantity: bigint, totalPaid: bigint, studioPaid: bigint, versePaid: bigint];
      export interface OutputObject {buyer: string, itemId: bigint, studio: string, quantity: bigint, totalPaid: bigint, studioPaid: bigint, versePaid: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ItemUpdatedEvent {
      export type InputTuple = [itemId: BigNumberish, priceXsolla: BigNumberish, active: boolean];
      export type OutputTuple = [itemId: bigint, priceXsolla: bigint, active: boolean];
      export interface OutputObject {itemId: bigint, priceXsolla: bigint, active: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PaymentRecipientUpdatedEvent {
      export type InputTuple = [recipient: AddressLike];
      export type OutputTuple = [recipient: string];
      export interface OutputObject {recipient: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StakeViewUpdatedEvent {
      export type InputTuple = [stakeView: AddressLike];
      export type OutputTuple = [stakeView: string];
      export interface OutputObject {stakeView: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StudioUpdatedEvent {
      export type InputTuple = [studio: AddressLike, allowed: boolean];
      export type OutputTuple = [studio: string, allowed: boolean];
      export interface OutputObject {studio: string, allowed: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface XsollaShop extends BaseContract {
    
    connect(runner?: ContractRunner | null): XsollaShop;
    waitForDeployment(): Promise<this>;

    interface: XsollaShopInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    MAX_STUDIO_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    buy: TypedContractMethod<
      [itemId: BigNumberish, quantity: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    games: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string, string, string, string, boolean] & {studio: string, name: string, blurb: string, coverURI: string, playUrl: string, platforms: string, active: boolean }],
      'view'
    >
    

    
    getGame: TypedContractMethod<
      [gameId: BigNumberish, ],
      [[string, string, string, string, string, string, boolean] & {studio: string, name_: string, blurb: string, coverURI: string, playUrl: string, platforms: string, active: boolean }],
      'view'
    >
    

    
    getListing: TypedContractMethod<
      [itemId: BigNumberish, ],
      [[bigint, boolean, string, string, string, string, string, string, bigint, boolean] & {priceXsolla: bigint, active: boolean, name_: string, metadataURI: string, game_: string, kind_: string, perk_: string, studio: string, studioBps: bigint, soulbound: boolean }],
      'view'
    >
    

    
    isStudio: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    itemGameId: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    items: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    listEcosystemItem: TypedContractMethod<
      [priceXsolla: BigNumberish, name_: string, metadataURI: string, game_: string, kind_: string, perk_: string, studio: AddressLike, studioBps: BigNumberish, soulbound_: boolean, ],
      [bigint],
      'nonpayable'
    >
    

    
    listForStudio: TypedContractMethod<
      [priceXsolla: BigNumberish, name_: string, metadataURI: string, gameId: BigNumberish, kind_: string, studioBps: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    listItem: TypedContractMethod<
      [priceXsolla: BigNumberish, name_: string, metadataURI: string, game_: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    listingEconomy: TypedContractMethod<
      [itemId: BigNumberish, ],
      [[string, bigint, boolean] & {studio: string, studioBps: bigint, soulbound: boolean }],
      'view'
    >
    

    
    listings: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, boolean, string, string, string, string, string, string, bigint, boolean] & {priceXsolla: bigint, active: boolean, name: string, metadataURI: string, game: string, kind: string, perk: string, studio: string, studioBps: bigint, soulbound: boolean }],
      'view'
    >
    

    
    nextGameId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    nextItemId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    paymentRecipient: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    registerGame: TypedContractMethod<
      [name_: string, blurb: string, coverURI: string, playUrl: string, platforms: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    registerGameFor: TypedContractMethod<
      [studio_: AddressLike, name_: string, blurb: string, coverURI: string, playUrl: string, platforms: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setPaymentRecipient: TypedContractMethod<
      [recipient: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setStakeView: TypedContractMethod<
      [stakeView_: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setStudio: TypedContractMethod<
      [studio: AddressLike, allowed: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    stakeView: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateItem: TypedContractMethod<
      [itemId: BigNumberish, priceXsolla: BigNumberish, active: boolean, name_: string, metadataURI: string, game_: string, ],
      [void],
      'nonpayable'
    >
    

    
    updateOwnGame: TypedContractMethod<
      [gameId: BigNumberish, name_: string, blurb: string, coverURI: string, playUrl: string, platforms: string, active: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    updateOwnItem: TypedContractMethod<
      [itemId: BigNumberish, priceXsolla: BigNumberish, active: boolean, name_: string, metadataURI: string, game_: string, ],
      [void],
      'nonpayable'
    >
    

    
    xsolla: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'MAX_STUDIO_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'buy'): TypedContractMethod<
      [itemId: BigNumberish, quantity: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'games'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string, string, string, string, boolean] & {studio: string, name: string, blurb: string, coverURI: string, playUrl: string, platforms: string, active: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'getGame'): TypedContractMethod<
      [gameId: BigNumberish, ],
      [[string, string, string, string, string, string, boolean] & {studio: string, name_: string, blurb: string, coverURI: string, playUrl: string, platforms: string, active: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'getListing'): TypedContractMethod<
      [itemId: BigNumberish, ],
      [[bigint, boolean, string, string, string, string, string, string, bigint, boolean] & {priceXsolla: bigint, active: boolean, name_: string, metadataURI: string, game_: string, kind_: string, perk_: string, studio: string, studioBps: bigint, soulbound: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'isStudio'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'itemGameId'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'items'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'listEcosystemItem'): TypedContractMethod<
      [priceXsolla: BigNumberish, name_: string, metadataURI: string, game_: string, kind_: string, perk_: string, studio: AddressLike, studioBps: BigNumberish, soulbound_: boolean, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'listForStudio'): TypedContractMethod<
      [priceXsolla: BigNumberish, name_: string, metadataURI: string, gameId: BigNumberish, kind_: string, studioBps: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'listItem'): TypedContractMethod<
      [priceXsolla: BigNumberish, name_: string, metadataURI: string, game_: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'listingEconomy'): TypedContractMethod<
      [itemId: BigNumberish, ],
      [[string, bigint, boolean] & {studio: string, studioBps: bigint, soulbound: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'listings'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, boolean, string, string, string, string, string, string, bigint, boolean] & {priceXsolla: bigint, active: boolean, name: string, metadataURI: string, game: string, kind: string, perk: string, studio: string, studioBps: bigint, soulbound: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'nextGameId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'nextItemId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'paymentRecipient'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'registerGame'): TypedContractMethod<
      [name_: string, blurb: string, coverURI: string, playUrl: string, platforms: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registerGameFor'): TypedContractMethod<
      [studio_: AddressLike, name_: string, blurb: string, coverURI: string, playUrl: string, platforms: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPaymentRecipient'): TypedContractMethod<
      [recipient: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setStakeView'): TypedContractMethod<
      [stakeView_: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setStudio'): TypedContractMethod<
      [studio: AddressLike, allowed: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'stakeView'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateItem'): TypedContractMethod<
      [itemId: BigNumberish, priceXsolla: BigNumberish, active: boolean, name_: string, metadataURI: string, game_: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateOwnGame'): TypedContractMethod<
      [gameId: BigNumberish, name_: string, blurb: string, coverURI: string, playUrl: string, platforms: string, active: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateOwnItem'): TypedContractMethod<
      [itemId: BigNumberish, priceXsolla: BigNumberish, active: boolean, name_: string, metadataURI: string, game_: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'xsolla'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'GameRegistered'): TypedContractEvent<GameRegisteredEvent.InputTuple, GameRegisteredEvent.OutputTuple, GameRegisteredEvent.OutputObject>;
getEvent(key: 'GameUpdated'): TypedContractEvent<GameUpdatedEvent.InputTuple, GameUpdatedEvent.OutputTuple, GameUpdatedEvent.OutputObject>;
getEvent(key: 'ItemListed'): TypedContractEvent<ItemListedEvent.InputTuple, ItemListedEvent.OutputTuple, ItemListedEvent.OutputObject>;
getEvent(key: 'ItemPurchased'): TypedContractEvent<ItemPurchasedEvent.InputTuple, ItemPurchasedEvent.OutputTuple, ItemPurchasedEvent.OutputObject>;
getEvent(key: 'ItemUpdated'): TypedContractEvent<ItemUpdatedEvent.InputTuple, ItemUpdatedEvent.OutputTuple, ItemUpdatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'PaymentRecipientUpdated'): TypedContractEvent<PaymentRecipientUpdatedEvent.InputTuple, PaymentRecipientUpdatedEvent.OutputTuple, PaymentRecipientUpdatedEvent.OutputObject>;
getEvent(key: 'StakeViewUpdated'): TypedContractEvent<StakeViewUpdatedEvent.InputTuple, StakeViewUpdatedEvent.OutputTuple, StakeViewUpdatedEvent.OutputObject>;
getEvent(key: 'StudioUpdated'): TypedContractEvent<StudioUpdatedEvent.InputTuple, StudioUpdatedEvent.OutputTuple, StudioUpdatedEvent.OutputObject>;

    filters: {
      
      'GameRegistered(uint256,address,string)': TypedContractEvent<GameRegisteredEvent.InputTuple, GameRegisteredEvent.OutputTuple, GameRegisteredEvent.OutputObject>;
      GameRegistered: TypedContractEvent<GameRegisteredEvent.InputTuple, GameRegisteredEvent.OutputTuple, GameRegisteredEvent.OutputObject>;
    

      'GameUpdated(uint256,string,bool)': TypedContractEvent<GameUpdatedEvent.InputTuple, GameUpdatedEvent.OutputTuple, GameUpdatedEvent.OutputObject>;
      GameUpdated: TypedContractEvent<GameUpdatedEvent.InputTuple, GameUpdatedEvent.OutputTuple, GameUpdatedEvent.OutputObject>;
    

      'ItemListed(uint256,uint256,string,string,string,string,address,uint16)': TypedContractEvent<ItemListedEvent.InputTuple, ItemListedEvent.OutputTuple, ItemListedEvent.OutputObject>;
      ItemListed: TypedContractEvent<ItemListedEvent.InputTuple, ItemListedEvent.OutputTuple, ItemListedEvent.OutputObject>;
    

      'ItemPurchased(address,uint256,address,uint256,uint256,uint256,uint256)': TypedContractEvent<ItemPurchasedEvent.InputTuple, ItemPurchasedEvent.OutputTuple, ItemPurchasedEvent.OutputObject>;
      ItemPurchased: TypedContractEvent<ItemPurchasedEvent.InputTuple, ItemPurchasedEvent.OutputTuple, ItemPurchasedEvent.OutputObject>;
    

      'ItemUpdated(uint256,uint256,bool)': TypedContractEvent<ItemUpdatedEvent.InputTuple, ItemUpdatedEvent.OutputTuple, ItemUpdatedEvent.OutputObject>;
      ItemUpdated: TypedContractEvent<ItemUpdatedEvent.InputTuple, ItemUpdatedEvent.OutputTuple, ItemUpdatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'PaymentRecipientUpdated(address)': TypedContractEvent<PaymentRecipientUpdatedEvent.InputTuple, PaymentRecipientUpdatedEvent.OutputTuple, PaymentRecipientUpdatedEvent.OutputObject>;
      PaymentRecipientUpdated: TypedContractEvent<PaymentRecipientUpdatedEvent.InputTuple, PaymentRecipientUpdatedEvent.OutputTuple, PaymentRecipientUpdatedEvent.OutputObject>;
    

      'StakeViewUpdated(address)': TypedContractEvent<StakeViewUpdatedEvent.InputTuple, StakeViewUpdatedEvent.OutputTuple, StakeViewUpdatedEvent.OutputObject>;
      StakeViewUpdated: TypedContractEvent<StakeViewUpdatedEvent.InputTuple, StakeViewUpdatedEvent.OutputTuple, StakeViewUpdatedEvent.OutputObject>;
    

      'StudioUpdated(address,bool)': TypedContractEvent<StudioUpdatedEvent.InputTuple, StudioUpdatedEvent.OutputTuple, StudioUpdatedEvent.OutputObject>;
      StudioUpdated: TypedContractEvent<StudioUpdatedEvent.InputTuple, StudioUpdatedEvent.OutputTuple, StudioUpdatedEvent.OutputObject>;
    
    };
  }