/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface XsollaItemsInterface extends Interface {
    getFunction(nameOrSignature: "balanceOf" | "balanceOfBatch" | "isApprovedForAll" | "mint" | "mintBatch" | "minter" | "name" | "owner" | "renounceOwnership" | "safeBatchTransferFrom" | "safeTransferFrom" | "setApprovalForAll" | "setMinter" | "setSoulbound" | "setTokenURI" | "soulbound" | "supportsInterface" | "symbol" | "transferOwnership" | "uri"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ApprovalForAll" | "MinterUpdated" | "OwnershipTransferred" | "SoulboundSet" | "TransferBatch" | "TransferSingle" | "URI" | "URISet"): EventFragment;

    encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'balanceOfBatch', values: [AddressLike[], BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'isApprovedForAll', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'mint', values: [AddressLike, BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'mintBatch', values: [AddressLike, BigNumberish[], BigNumberish[], BytesLike]): string;
encodeFunctionData(functionFragment: 'minter', values?: undefined): string;
encodeFunctionData(functionFragment: 'name', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'safeBatchTransferFrom', values: [AddressLike, AddressLike, BigNumberish[], BigNumberish[], BytesLike]): string;
encodeFunctionData(functionFragment: 'safeTransferFrom', values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'setApprovalForAll', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setMinter', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setSoulbound', values: [BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'setTokenURI', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'soulbound', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'symbol', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'uri', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOfBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isApprovedForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'minter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeBatchTransferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeTransferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setApprovalForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMinter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setSoulbound', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTokenURI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'soulbound', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'symbol', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'uri', data: BytesLike): Result;
  }

  
    export namespace ApprovalForAllEvent {
      export type InputTuple = [account: AddressLike, operator: AddressLike, approved: boolean];
      export type OutputTuple = [account: string, operator: string, approved: boolean];
      export interface OutputObject {account: string, operator: string, approved: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MinterUpdatedEvent {
      export type InputTuple = [minter: AddressLike];
      export type OutputTuple = [minter: string];
      export interface OutputObject {minter: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SoulboundSetEvent {
      export type InputTuple = [id: BigNumberish, soulbound: boolean];
      export type OutputTuple = [id: bigint, soulbound: boolean];
      export interface OutputObject {id: bigint, soulbound: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferBatchEvent {
      export type InputTuple = [operator: AddressLike, from: AddressLike, to: AddressLike, ids: BigNumberish[], values: BigNumberish[]];
      export type OutputTuple = [operator: string, from: string, to: string, ids: bigint[], values: bigint[]];
      export interface OutputObject {operator: string, from: string, to: string, ids: bigint[], values: bigint[] };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferSingleEvent {
      export type InputTuple = [operator: AddressLike, from: AddressLike, to: AddressLike, id: BigNumberish, value: BigNumberish];
      export type OutputTuple = [operator: string, from: string, to: string, id: bigint, value: bigint];
      export interface OutputObject {operator: string, from: string, to: string, id: bigint, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace URIEvent {
      export type InputTuple = [value: string, id: BigNumberish];
      export type OutputTuple = [value: string, id: bigint];
      export interface OutputObject {value: string, id: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace URISetEvent {
      export type InputTuple = [id: BigNumberish, uri: string];
      export type OutputTuple = [id: bigint, uri: string];
      export interface OutputObject {id: bigint, uri: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface XsollaItems extends BaseContract {
    
    connect(runner?: ContractRunner | null): XsollaItems;
    waitForDeployment(): Promise<this>;

    interface: XsollaItemsInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    balanceOf: TypedContractMethod<
      [account: AddressLike, id: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    balanceOfBatch: TypedContractMethod<
      [accounts: AddressLike[], ids: BigNumberish[], ],
      [bigint[]],
      'view'
    >
    

    
    isApprovedForAll: TypedContractMethod<
      [account: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    mint: TypedContractMethod<
      [to: AddressLike, id: BigNumberish, amount: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    mintBatch: TypedContractMethod<
      [to: AddressLike, ids: BigNumberish[], amounts: BigNumberish[], data: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    minter: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    name: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    safeBatchTransferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, ids: BigNumberish[], values: BigNumberish[], data: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    safeTransferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, id: BigNumberish, value: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    setApprovalForAll: TypedContractMethod<
      [operator: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setMinter: TypedContractMethod<
      [newMinter: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setSoulbound: TypedContractMethod<
      [id: BigNumberish, value: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setTokenURI: TypedContractMethod<
      [id: BigNumberish, tokenURI_: string, ],
      [void],
      'nonpayable'
    >
    

    
    soulbound: TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    symbol: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    uri: TypedContractMethod<
      [id: BigNumberish, ],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [account: AddressLike, id: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'balanceOfBatch'): TypedContractMethod<
      [accounts: AddressLike[], ids: BigNumberish[], ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'isApprovedForAll'): TypedContractMethod<
      [account: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'mint'): TypedContractMethod<
      [to: AddressLike, id: BigNumberish, amount: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'mintBatch'): TypedContractMethod<
      [to: AddressLike, ids: BigNumberish[], amounts: BigNumberish[], data: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'minter'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'safeBatchTransferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, ids: BigNumberish[], values: BigNumberish[], data: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'safeTransferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, id: BigNumberish, value: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setApprovalForAll'): TypedContractMethod<
      [operator: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMinter'): TypedContractMethod<
      [newMinter: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setSoulbound'): TypedContractMethod<
      [id: BigNumberish, value: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTokenURI'): TypedContractMethod<
      [id: BigNumberish, tokenURI_: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'soulbound'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'symbol'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'uri'): TypedContractMethod<
      [id: BigNumberish, ],
      [string],
      'view'
    >;

    getEvent(key: 'ApprovalForAll'): TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
getEvent(key: 'MinterUpdated'): TypedContractEvent<MinterUpdatedEvent.InputTuple, MinterUpdatedEvent.OutputTuple, MinterUpdatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'SoulboundSet'): TypedContractEvent<SoulboundSetEvent.InputTuple, SoulboundSetEvent.OutputTuple, SoulboundSetEvent.OutputObject>;
getEvent(key: 'TransferBatch'): TypedContractEvent<TransferBatchEvent.InputTuple, TransferBatchEvent.OutputTuple, TransferBatchEvent.OutputObject>;
getEvent(key: 'TransferSingle'): TypedContractEvent<TransferSingleEvent.InputTuple, TransferSingleEvent.OutputTuple, TransferSingleEvent.OutputObject>;
getEvent(key: 'URI'): TypedContractEvent<URIEvent.InputTuple, URIEvent.OutputTuple, URIEvent.OutputObject>;
getEvent(key: 'URISet'): TypedContractEvent<URISetEvent.InputTuple, URISetEvent.OutputTuple, URISetEvent.OutputObject>;

    filters: {
      
      'ApprovalForAll(address,address,bool)': TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
      ApprovalForAll: TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
    

      'MinterUpdated(address)': TypedContractEvent<MinterUpdatedEvent.InputTuple, MinterUpdatedEvent.OutputTuple, MinterUpdatedEvent.OutputObject>;
      MinterUpdated: TypedContractEvent<MinterUpdatedEvent.InputTuple, MinterUpdatedEvent.OutputTuple, MinterUpdatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'SoulboundSet(uint256,bool)': TypedContractEvent<SoulboundSetEvent.InputTuple, SoulboundSetEvent.OutputTuple, SoulboundSetEvent.OutputObject>;
      SoulboundSet: TypedContractEvent<SoulboundSetEvent.InputTuple, SoulboundSetEvent.OutputTuple, SoulboundSetEvent.OutputObject>;
    

      'TransferBatch(address,address,address,uint256[],uint256[])': TypedContractEvent<TransferBatchEvent.InputTuple, TransferBatchEvent.OutputTuple, TransferBatchEvent.OutputObject>;
      TransferBatch: TypedContractEvent<TransferBatchEvent.InputTuple, TransferBatchEvent.OutputTuple, TransferBatchEvent.OutputObject>;
    

      'TransferSingle(address,address,address,uint256,uint256)': TypedContractEvent<TransferSingleEvent.InputTuple, TransferSingleEvent.OutputTuple, TransferSingleEvent.OutputObject>;
      TransferSingle: TypedContractEvent<TransferSingleEvent.InputTuple, TransferSingleEvent.OutputTuple, TransferSingleEvent.OutputObject>;
    

      'URI(string,uint256)': TypedContractEvent<URIEvent.InputTuple, URIEvent.OutputTuple, URIEvent.OutputObject>;
      URI: TypedContractEvent<URIEvent.InputTuple, URIEvent.OutputTuple, URIEvent.OutputObject>;
    

      'URISet(uint256,string)': TypedContractEvent<URISetEvent.InputTuple, URISetEvent.OutputTuple, URISetEvent.OutputObject>;
      URISet: TypedContractEvent<URISetEvent.InputTuple, URISetEvent.OutputTuple, URISetEvent.OutputObject>;
    
    };
  }